### PR TITLE
Changed file ext to .cs and Magnum -> PortableMagnum

### PR DESCRIPTION
**Pull request by rico345100**
You can just keep name "Magnum" but you must change the GameObject of revolver(which child of WeaponManager gameobject) to "Magnum" as well.

After review the code, please close the pull request. If you have additional question, leave comment in the below and don't close the PR so that I can keep check it.

### CODE REVIEW

**Review by rico345100 — COMMENTED** [review]
You can just keep name "Magnum" but you must change the GameObject of revolver(which child of WeaponManager gameobject) to "Magnum" as well.

**Comment by Pr4th** [comment]
so does that mean private Weapon primaryWeapon = Weapon.UMP45;


 private Weapon primaryWeapon = Weapon.Magnum; ????

**Comment by rico345100** [comment]
Why are you putting Weapon.UMP45 in primaryWeapon? It doesn't matter, only you have to do is change object name of "PortableMagnum" to "Magnum" or change enum "Magnum" -> "PortableMagnum". In my tutorial series, I'm using PortableMagnum so I recommend do to same to avoid future confusion.

**Comment by Pr4th** [comment]
i did it but i still get the same error

**Comment by rico345100** [comment]
Did it which? Take screenshot of childs of WeaponManager object. I don't know it's named WeaponManager but I mean the game object which have WeaponManager component.

**Comment by Pr4th** [comment]
i am afraid i dont see any weapon manager object in the code, do you want to chat and try to find it out

**Comment by rico345100** [comment]
http://photon.modernator.me:/album/rico345100@gmail.com/others//K-1813%20copy.png

**Comment by Pr4th** [comment]
https://golep1234.tumblr.com/post/186237275944

?????

**Comment by rico345100** [comment]
To make that work, in your script don't change to PortableMagnum. I don't know how many times talking same thing. Keep the same name with your enum value for Magnum and GameObject's name inside of WeaponManager gameobject. @Pr4th

**Comment by Pr4th** [comment]
i did that. I put Magnum in the enum, but the error persists

**Comment by Pr4th** [comment]
@rico345100  ok i think i figured it out, thanks for trying to help anyways I am pretty sure you were annoyed when you were reading my questions.

**Comment by rico345100** [comment]
I'm not annoyed from your question. But next time don't do something like "???????" stuff. That makes me little bit upset. I'm not sure what was that mean, but to me, it seems like "what are you talking?? I'm already did dude."

Anyway glad you fixed your problem. Questions are welcome but please dont do that something like that again. Closing this.

**Comment by Pr4th** [comment]
oh yeah next time i will use words sorry man, i just get very frustrated when i cant see small things that are difficult to find. Especially with this project because so many things are intertwined you never know why you are getting an error

**Pull request closed without merging**
